[project]
name = "robotic-swarmalator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10.6"
dependencies = [
    "matplotlib>=3.10.1",
    "numpy>=2.2.5",
]
